package cd.lan1akea.core.message;

/**
 * Name MessageRole.java
 * Author lan1akea
 * Date 2026/06/21
 */
public enum MessageRole {

    /**
     * User role for messages from human users or external inputs.
     *
     * <p>These messages typically contain user questions, commands, or input data
     * that the agent needs to process or respond to.
     */
    USER,

    /**
     * Assistant role for messages generated by AI agents or assistants.
     *
     * <p>These messages contain the agent's responses, reasoning, or actions
     * in response to user messages or system prompts.
     */
    ASSISTANT,

    /**
     * System role for system instructions, prompts, or configuration messages.
     *
     * <p>These messages typically contain setup instructions, context information,
     * or system-level directives that guide agent behavior.
     */
    SYSTEM,

    /**
     * Tool role for messages containing tool execution results or responses.
     *
     * <p>These messages contain the output from tool executions, including
     * return values, error messages, or status information from external tools.
     */
    TOOL
}
